baseURL = "https://pedroprieto.github.io"
title = "Blog de Pedro Prieto"
theme = "jane"
enableRobotsTXT = true
paginate = 3

pygmentsCodeFences = true
pygmentsStyle = "native"
# pygmentsOptions = "linenos=true"

defaultContentLanguage = "es"
[languages.es]
  languageCode = "es"

[author]
  name = "Pedro Prieto Alarcón"

[[menu.main]]
  name = "Inicio"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archivo"
  weight = 20
  identifier = "archives"
  url = "/post"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categorías"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  keywords = ["DIW", "interfaces", "DAW", "desarrollo web"]
  description = "Blog profesional de Pedro Prieto"
  dateFormatToUse = "02-01-2006"
  contentCopyright = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>'
  [params.social]
    a-email = "mailto:pedroprieto@iesmarenostrum.com"
    g-github = "https://github.com/pedroprieto"